server:
  port: 8080
  error:
    include-stacktrace: always

Spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/airport_ms_db?createDatabaseIfNotExist=true
    username: root
    password: